---
abstract: 'Xslate(TTerse) + Otogiri + alpha'
author:
  - 'ytnobody <ytnobody@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.5, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nephia-Setup-Plugin-Relax
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Nephia::Setup::Plugin::Relax:
    file: lib/Nephia/Setup/Plugin/Relax.pm
    version: 0.02
requires:
  Nephia: 0.86
  Nephia::Setup::Plugin::Assets::Bootstrap: 0.04
  Nephia::Setup::Plugin::Assets::JQuery: 0.03
  perl: 5.008005
resources:
  bugtracker: https://github.com/nephia/Nephia-Setup-Plugin-Relax/issues
  homepage: https://github.com/nephia/Nephia-Setup-Plugin-Relax
  repository: git://github.com/nephia/Nephia-Setup-Plugin-Relax.git
version: 0.02
x_contributors:
  - 'papix <mail@papix.net>'
